version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@adonisjs/bodyparser"
    versions:
    - 7.0.0
    - 7.0.1
  - dependency-name: "@adonisjs/ace"
    versions:
    - 10.0.0
    - 10.0.1
    - 9.1.0
  - dependency-name: "@adonisjs/auth"
    versions:
    - 4.3.1
  - dependency-name: "@adonisjs/lucid"
    versions:
    - 12.0.0
  - dependency-name: sqlite3
    versions:
    - 5.0.1
